# -*- coding: utf-8 -*-
"""Modulo_3_Sessao_1_Ex_2_Eqp_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X1eL_xGW-LKCOM9q0lEPT8Mdg3X0VAZD
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv ("/content/drive/MyDrive/Colab Notebooks/laptop_pricing.csv")
df

df = df[["Manufacturer", "Screen_Size_cm", "Price"]]
df

# 1. Moda Manufacturer

df['Manufacturer'].value_counts().idxmax()

# 1. Medidas Screen Size

print('Moda: ', df['Screen_Size_cm'].value_counts().idxmax())
print('Média : ',df['Screen_Size_cm'].mean())
print('Mediana: ',df['Screen_Size_cm'].median())
print('Mínimo: ',df['Screen_Size_cm'].min())
print('Máximo: ',df['Screen_Size_cm'].max())

print('Q1: ',df['Screen_Size_cm'].quantile(0.25))
print('Q3: ',df['Screen_Size_cm'].quantile(0.75))

print('IQR:', df['Screen_Size_cm'].quantile(0.75)-df['Screen_Size_cm'].quantile(0.25))

print('IQR (Amplitude Interquartil):', iqr)
print('Desvio Padão: ', df['Screen_Size_cm'].std())
amplitude = df['Screen_Size_cm'].max() - df['Screen_Size_cm'].min()
print('Amplitude Total: ', amplitude)
print('Skew: ',df['Screen_Size_cm'].skew())

# 1. Medidas Price

print('Moda: ', df['Price'].value_counts().idxmax())
print('Média : ',df['Price'].mean())
print('Mediana: ',df['Price'].median())
print('Mínimo: ',df['Price'].min())
print('Máximo: ',df['Price'].max())
print('Q1: ',df['Price'].quantile(0.25))
print('Q3: ',df['Price'].quantile(0.75))
print('IQR:', df['Price'].quantile(0.75)-df['Price'].quantile(0.25))

print('Desvio Padão: ', df['Price'].std())
amplitude = df['Price'].max() - df['Price'].min()
print('Amplitude Total: ', amplitude)
print('Skew: ',df['Price'].skew())

#Price

plt.figure(figsize=(10, 6))

sns.histplot(df['Price'], bins=15, kde=True, color='skyblue')

plt.title('Distribuição de Frequência dos Preços', fontsize=15)
plt.xlabel('Preço (Euros)')
plt.ylabel('Quantidade')

plt.show()

#Manufacturer
df['Manufacturer'].value_counts().plot(kind='bar')
plt.title('Distribuição por Marca')
plt.xlabel('Fabricante')
plt.ylabel('Frequência')
plt.xticks(rotation=45)
plt.show()

#Screen Size

plt.figure(figsize=(10, 6))

sns.histplot(df['Screen_Size_cm'], bins=15, kde=True, color='skyblue')

plt.title('Distribuição de Frequência do Tamanho Tela', fontsize=15)
plt.xlabel('Tamanho (Cm)')
plt.ylabel('Quantidade')

plt.show()

# Correlação entre Screen size e Price
plt.scatter(df['Screen_Size_cm'], df['Price'])

pivot_table = df.pivot_table(index='Manufacturer',
                             columns='Screen_Size_cm',
                             values='Price',
                             aggfunc='mean')
plt.figure(figsize=(12, 8))
sns.heatmap(pivot_table, annot=True, fmt=".0f", cmap='YlGnBu', linewidths=.5)

plt.title('Mapa de Calor: Preço Médio por Marca e Screen Size', fontsize=15)
plt.xlabel('Screen Size (cm)')
plt.ylabel('Fabricante (Manufacturer)')

plt.show()

"""Entre Price e Screen size não há uma correlação linear.
No caso do Manufacturer, por se tratar de uma variável qualitativa  nominal, não é possível analisar uma relação linear, mas sim comparar a distribuição dos preços entre diferentes fabricantes.
"""